FROM node:20.9.0 AS build

WORKDIR /home/dewe-tour-nest

COPY . .

RUN npm install -g pnpm

RUN pnpm install
RUN pnpm run build

FROM node:20.9.0-alpine

WORKDIR /home/dewe-tour-nest

COPY --from=build /home/dewe-tour-nest/dist ./src
COPY --from=build /home/dewe-tour-nest/node_modules ./node_modules

EXPOSE 5000

CMD ["node", "src/main.js"]